name: Publish Nuget package
on:
  push:
    branches:
    - master
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: BlazorCharts
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Update Nuget package
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}   
    - name: Build solution and generate NuGet package
      run: |  
        cd ${{ env.WORKING_DIRECTORY }}
        dotnet pack -c Release -o out 
    - name: Publish Artifacts
      run: dotnet nuget push ./${{ env.WORKING_DIRECTORY }}/out/*.nupkg --skip-duplicate --no-symbols true